/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel.orcamento.app

import com.natpryce.konfig.ConfigurationMap
import kong.unirest.Unirest
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.*

private const val PORT_NUMBER = "3000"

class AppTest {

    private val config = ConfigurationMap(
        "port" to PORT_NUMBER,
        "javalin.show-javalin-banner" to "false"
    )

    private val app = App(config)

    @BeforeAll
    internal fun setUp() {
        app.start()
    }

    @AfterAll
    internal fun tearDown() {
        app.stop()
    }

    @Test
    fun `inicia o servidor na porta especificada na configuração`() {
        val response = Unirest.get("http://localhost:$PORT_NUMBER").asString()

        assertThat(response.status).isEqualTo(200)
    }

    @Test
    internal fun `renderiza home page`() {
        val response = Unirest.get("http://localhost:$PORT_NUMBER").asString()

        assertThat(response.body).contains("<title>Orçamento Semanal")
    }
}
