/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel.orcamento.app

import io.javalin.Javalin

class App(appConfiguration: AppConfiguration) {
    private val config = appConfiguration
    private val server: Javalin = Javalin.create()

    fun start() {
        server.get("/") { ctx ->
            ctx.render("home.peb")
        }

        config.showJavalinBanner?.let {
            server.config.showJavalinBanner = it
        }

        config.port
                ?.let { server.start(it) }
                ?: start()
    }

    fun stop() {
        server.stop()
    }
}

