/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel.orcamento.app

import io.javalin.Javalin

class App(appConfiguration: AppConfiguration) {
    private val config = appConfiguration
    private val javalin = Javalin
            .create(config::applyTo)
            .get("/") { ctx ->
                ctx.render("home.peb")
            }

    fun start() {
        config.useToStart(javalin)
    }

    fun stop() {
        javalin.stop()
    }
}

