/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel

import com.natpryce.konfig.ConfigurationMap
import kong.unirest.Unirest
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

private const val PORT_NUMBER = "3000"

class AppTest {

    private val config = ConfigurationMap("port" to PORT_NUMBER)
    private val app = App(config)

    @BeforeEach
    internal fun setUp() {
        app.start()
    }

    @AfterEach
    internal fun tearDown() {
        app.stop()
    }

    @Test
    fun `inicia o servidor na porta especificada na configuração`() {
        val response = Unirest.get("http://localhost:$PORT_NUMBER").asString()

        assertThat(response.status).isEqualTo(200)
        assertThat(response.body).isEqualTo("OK")
    }
}
