/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package codes.pedromanoel

import com.natpryce.konfig.*
import com.natpryce.konfig.ConfigurationProperties.Companion.fromOptionalFile
import io.javalin.Javalin
import java.io.File

class App(
    private val config: Configuration
) {
    private val server: Javalin = Javalin.create()

    private val port by intType

    fun start() {
        server
            .get("/") { ctx ->
                ctx.result("OK")
            }
            .start(config[port])
    }

    fun stop() {
        server.stop()
    }
}

fun main(args: Array<String>) {
    val config: Configuration = EnvironmentVariables() overriding
            fromOptionalFile(File("./application.properties"))

    val app = App(config)

    shutdownHook {
        app.stop()
    }

    app.start()
}

private fun shutdownHook(shutdownCallback: () -> Unit) {
    Runtime.getRuntime().addShutdownHook(Thread(shutdownCallback))
}
